// Code generated by generator - dev. DO NOT EDIT.

package example

import (
	"context"
	"fmt"
	"strconv"
)

// execute runs createUserOp.validate, and createUserOp.handle in sequence.
func (op *createUserOp) execute(ctx context.Context, input CreateUserInput) error {
	v0 := op.validate(ctx, input)
	if v0 != nil {
		return fmt.Errorf("validate: %w", v0)
	}

	v1 := op.handle(ctx, input)
	if v1 != nil {
		return fmt.Errorf("handle: %w", v1)
	}

	return nil
}

// execute runs updateUserOp.validate, updateUserOp.authorize, and
// updateUserOp.handle in sequence.
func (op *updateUserOp) execute(ctx context.Context, input UpdateUserInput) error {
	v0, v1 := op.validate(ctx, input)
	if v1 != nil {
		return fmt.Errorf("validate: %w", v1)
	}

	v2 := op.authorize(input, v0)
	if v2 != nil {
		return fmt.Errorf("authorize: %w", v2)
	}

	v3 := op.handle(ctx, input)
	if v3 != nil {
		return fmt.Errorf("handle: %w", v3)
	}

	return nil
}

type serviceImpl struct {
	createUserOp *createUserOp
	updateUserOp *updateUserOp
}

func (s *serviceImpl) CreateUser(ctx context.Context, input CreateUserInput) error {
	return s.createUserOp.execute(ctx, input)
}

func (s *serviceImpl) UpdateUser(ctx context.Context, input UpdateUserInput) error {
	return s.updateUserOp.execute(ctx, input)
}

type serviceDeps struct {
	repository Repository
	mailer     Mailer
}

func newService(deps *serviceDeps) *serviceImpl {
	impl := &serviceImpl{
		createUserOp: &createUserOp{
			mailer:     deps.mailer,
			repository: deps.repository,
		},
		updateUserOp: &updateUserOp{
			mailer:     deps.mailer,
			repository: deps.repository,
		},
	}
	return impl
}

// Unnamed variable used to ensure `import "strconv"` is generated, as it is required below.
var _ = strconv.FormatInt(0, 10)

// --- Code generated by go run golang.org/x/tools/cmd/stringer@latest -type Status -linecomment -output /dev/stdout

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusInactive-0]
	_ = x[StatusActive-1]
}

const _Status_name = "inactiveStatusActive"

var _Status_index = [...]uint8{0, 8, 20}

func (i Status) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Status_index)-1 {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[idx]:_Status_index[idx+1]]
}

// --- End code generated by go run golang.org/x/tools/cmd/stringer@latest -type Status -linecomment -output /dev/stdout
