// Code generated by generator - dev. DO NOT EDIT.

package api

import (
	"context"
	"fmt"
)

// handle runs awesomeAPI.parse, awesomeAPI.invoke, and awesomeAPI.response in
// sequence.
func (op *awesomeAPI) handle(ctx context.Context, request Request) (Response, error) {
	v0, v1 := op.parse(ctx, request)
	if v1 != nil {
		return Response{}, fmt.Errorf("parse: %w", v1)
	}

	v2, v3 := op.invoke(ctx, v0)
	if v3 != nil {
		return Response{}, fmt.Errorf("invoke: %w", v3)
	}

	v4, v5 := op.response(ctx, v2)
	if v5 != nil {
		return Response{}, fmt.Errorf("response: %w", v5)
	}

	return v4, nil
}
